### ISSUE TITLE
Great workshop!  Found a scoring bug maybe?

### ISSUE THREAD

**Issue by colinta** [DinnerBuffet/TTSCarcassonne#3]
I'm about to jump into the code to see if I can solve this one myself, but I'll bring it up here in case I'm mistaken.  I noticed during my first TTS Carcassonne game last night that when I scored a two-tiled city it scored *four* points instead of two.  I verified this later.

At the end of the game, though, I saw that the total included some `-2` entries - maybe those are corrections?  Even if so I think the scoring could be corrected - should be as easy as `if score == 4, score = 2`

**Comment by colinta** [comment]
Well I did a scan of the lua files and couldn't find obvious "score the city tiles" code.  My god so much code here!  Hell of a good job, too.  Thanks for maintaining this.

**Comment by colinta** [comment]
Ahhh and now I'm reading that this is a "3rd edition" change to the rules that I never heard about!  Good to know.

**Comment by DinnerBuffet** [comment]
Yes you're right that the rules were changed quite long ago. FYI there is an option on the 6th page of the control panel to revert to these old rules and only score 2 points. Not sure if it works, though.

**Comment by tntmonty** [comment]
Thanks for the mod - a great find given we can't play locally at the moment. I've been caught out by by the scoring, as the tablet seems to point to the first edition rules but then says a city scores 3 in a field, and the mod notebook has a scoring of 4 for each complete city in a field, but the mod itself seems to use the 3rd edition rules. Is it right that the mod is aiming for 3rd edition rules? I'd happy help update the notebook, but I can't find that info in github (but I'm new to this stuff, so apologies if it's obvious to you).
