### ISSUE TITLE
Abbot mini expansion

### ISSUE THREAD

**Issue by Nicholaiii** [DinnerBuffet/TTSCarcassonne#4]
Any plans to include this? It's a real nice addition to the base game

**Comment by DinnerBuffet** [comment]
The Abbot is already included, but is not implemented in the control panel. You just need to pull out the tiles and abbots from the Carcassonne II bag before starting the game. I didn't implement Carcassonne II features/tiles in the control panel yet. Not sure if I'll ever get to it.

**Comment by lilasquared** [comment]
@DinnerBuffet in order to use the abbot and garden tiles do you need to replace the equivalent ones from the main stack, or do you just replace the entire stack?  We loving using this version but were missing out on the abbot.  Will it score accordingly and allow you to remove the abbot ahead of time or will that require manual intervention in the scoring and game flow?

**Comment by DinnerBuffet** [comment]
@lilasquared The Carcassonne II tile stack should have the exact same tiles, just with the addition of gardens on some, so you can toss the entire original stack if you want. Fun fact, though, you don't _need_ to. Carcassonne I and Carcassonne II tiles are essentially the same and you can mix them as you want, including any Carcassonne I expansions. It would just be rather ugly.

Abbot should be fully scripted and not require any manual intervention once it is setup. Though I admit I haven't used it in a long time so I'm not sure if it still works.

Side-note: there are a ton of implemented expansions that people rarely play with and it's not uncommon to get reports of expansions that have been broken for years. Please report them if you happen to run into them!

**Comment by DinnerBuffet** [comment]
Closing this. Tracking on Trello here: https://trello.com/c/gu67SAb6/14-add-carcassonne-v2-tiles-to-control-panel
