### ISSUE TITLE
Tiles moving top away from border confuses scripts

### ISSUE THREAD

**Issue by sebastianbergt** [DinnerBuffet/TTSCarcassonne#5]
Thank you for this amazing mod! I ran into an error today.

After placing a tile next to the upper border of the playing table (see screenshot attached). The mod is confused and throws lua errors. Placing tiles is no longer works. Playing with two players.
![Screenshot from 2020-04-07 21-53-02](https://user-images.githubusercontent.com/2187920/78713913-45c77980-791b-11ea-902e-1e30a9b46835.jpeg)

**Comment by DinnerBuffet** [comment]
Thanks for the bug report! I'll try to reproduce this and fix it soon.

**Comment by DinnerBuffet** [comment]
I was able to reproduce the problem and I think I've narrowed down the cause. Looks like you found a bug that's been there for a very long time and was made more prevalent by a slightly more recent refactor that I did. I would avoid putting tiles at the edges until I can come up with a fix, which should hopefully be in the next few days.

**Comment by DinnerBuffet** [comment]
I have a fix ready. Will release it with 1.22.2.

**Comment by DinnerBuffet** [comment]
Uploaded new version.
