### ISSUE TITLE
The Wagon - Adjacent Features

### ISSUE THREAD

**Issue by lilasquared** [DinnerBuffet/TTSCarcassonne#9]
The rules for the wagon on on [this link](https://images.zmangames.com/filer_public/48/90/48909233-453b-446f-bbb6-3aee9058a41b/zm7815_carcassonne_exp5_rules.pdf) indicate that the wagon must be placed on a feature adjacent to the tile the wagon is on at the time of scoring.  It looks like the rules in your version are showing hints for features that are only connected via roads (or something like that).  Is this a different rule set that you are using, and is there a way to toggle between them?

**Comment by DinnerBuffet** [comment]
Those rules are for the new edition of Carcassonne. The mod implements rules for the original edition of the game.

Please see here: http://wikicarpedia.com/index.php/Main_Page#First_edition_rules

**Comment by DinnerBuffet** [comment]
and no, there is no way to toggle between them, but you are always welcome to add the code for it yourself.

**Comment by lilasquared** [comment]
awesome thanks!
